sbatch scripts/Llama-2-7b-chat-hf-0.1-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.1-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.1-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.1-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.1-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.1-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.1-0.6-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.1-0.7-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.1-0.8-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.2-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.2-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.2-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.2-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.2-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.2-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.2-0.6-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.2-0.7-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.3-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.3-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.3-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.3-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.3-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.3-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.3-0.6-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.4-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.4-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.4-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.4-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.4-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.4-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.5-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.5-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.5-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.5-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.5-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.6-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.6-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.6-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.6-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.7-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.7-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.7-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.8-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.8-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-7b-chat-hf-0.9-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.1-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.1-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.1-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.1-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.1-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.1-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.1-0.6-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.1-0.7-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.1-0.8-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.2-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.2-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.2-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.2-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.2-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.2-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.2-0.6-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.2-0.7-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.3-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.3-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.3-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.3-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.3-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.3-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.3-0.6-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.4-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.4-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.4-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.4-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.4-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.4-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.5-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.5-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.5-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.5-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.5-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.6-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.6-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.6-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.6-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.7-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.7-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.7-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.8-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.8-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-0.9-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.1-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.1-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.1-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.1-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.1-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.1-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.1-0.6-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.1-0.7-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.1-0.8-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.2-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.2-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.2-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.2-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.2-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.2-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.2-0.6-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.2-0.7-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.3-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.3-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.3-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.3-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.3-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.3-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.3-0.6-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.4-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.4-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.4-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.4-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.4-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.4-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.5-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.5-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.5-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.5-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.5-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.6-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.6-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.6-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.6-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.7-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.7-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.7-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.8-0-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.8-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Llama-2-13b-chat-hf-0.9-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.1-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.1-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.1-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.1-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.1-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.1-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.1-0.6-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.1-0.7-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.1-0.8-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.2-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.2-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.2-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.2-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.2-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.2-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.2-0.6-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.2-0.7-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.3-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.3-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.3-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.3-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.3-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.3-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.3-0.6-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.4-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.4-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.4-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.4-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.4-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.4-0.5-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.5-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.5-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.5-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.5-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.5-0.4-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.6-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.6-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.6-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.6-0.3-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.7-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.7-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.7-0.2-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.8-0-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.8-0.1-anns_es-mgpANNSES.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-0.9-0-anns_es-mgpANNSES.sh
